services:
  backend:
    #image: backend
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
 
    volumes:
      - ./backend/src:/app/src
      - ./backend/db:/app/db
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
  
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=healthdiary
    depends_on:
      - mongo
    

  frontend:
    #image: frontend
    #pull_policy: never
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents local node_modules from overriding container ones
    environment:
      - VITE_API_URL=http://backend:5000 # Use backend service name
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: